# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_name: <%= ENV["YAMS_ADMIN_NAME"] %>
  admin_email: <%= ENV["YAMS_ADMIN_EMAIL"] %>
  admin_password: <%= ENV["YAMS_ADMIN_PASSWORD"] %>
  domain_name: yams.fm
  secret_key_base: <%= ENV["YAMS_SECRET_KEY_BASE"] %>

# shared:
#   api_key: a1B2c3D4e5F6

test:
  domain_name: example.com 
  secret_key_base: 9686a64745d120d7c04f177bdc0891324c67140480ea63caf231fc6d7c4cf3f0849fa9aee34af056e3e0cb8188e30cc7828497eaf4b3360fdfcd30230a5ff5e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  admin_name: <%= ENV["YAMS_ADMIN_NAME"] %>
  admin_email: <%= ENV["YAMS_ADMIN_EMAIL"] %>
  domain_name: <%= ENV["YAMS_EMAIL_DOMAIN"] %>
  secret_key_base: <%= ENV["YAMS_SECRET_KEY_BASE"] %>
  email_provider_username:  <%= ENV["YAMS_EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password:  <%= ENV["YAMS_EMAIL_PROVIDER_PASSWORD"] %>
  email_port:  <%= ENV["YAMS_EMAIL_PORT"].to_i %>
  enable_starttls_auto: <%= ENV["YAMS_ENABLE_STARTTLS_AUTO"].to_s.downcase == 'true' %>

