# Specific Config for yams99 Server. Uses external MySQL server
#
#   docker-compose -f docker-compose.yml -f docker/services/yams99.yml build --no-cache web_mis99
#
#   docker-compose -f docker-compose.yml -f docker/services/yams99.yml up -d web_mis99
#
# https://docs.docker.com/compose/compose-file/
#
# Nice management UI for Docker : https://github.com/portainer/portainer
# This creates a local (development) style installation, availble at http://http://docker.yams/yams
# Note:  Requires following entry in your local /etc/hosts
#   127.0.0.1 yams.docker
#
version: '3'

services:

  development:
    build:
      context: .
      args:                           # Build Arguments
       RAILS_ENV: development
       RUBY_VERSION: 2.5.1
       BUNDLE_INSTALL_ARGS: '--jobs 20 --retry 5'
    container_name: development
    environment:                      # Runtime Arguments
      - RAILS_ENV=development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOGSTASH_HOST=logstash
      - VIRTUAL_HOST=docker.yams
    ports:
      - "636:636"     # LDAP
      - "80:80"       # Nginx
    volumes:
      - rails_logs_volume:/home/app/yams/log/
      - .env:/home/app/yams/.env
      - ./docker/config/database.yml:/home/app/yams/config/database.yml
      - ./docker/nginx/development.conf:/etc/nginx/sites-enabled/development.conf
    depends_on:
      - db
      - elasticsearch
      - kibana
      - redis
    links:
      - db
      - elasticsearch
      - kibana
      - redis

